
export const GET_GITHUB_API_DATA = 'GET_GITHUB_API_DATA';
export const GET_GITHUB_API_REPO_DATA = 'GET_GITHUB_API_REPO_DATA';

export const USER_PROFILE = "USER_PROFILE";
export const DESCRIPTION = "DESCRIPTION";
